image: node:lts

variables:
  DOCS_FOLDER: docs
  MARP_CUSTOM_THEME: css/dracula.css

before_script:
  - npm install -g markdownlint-cli
  - npm install -g @marp-team/marp-cli

ci:
  stage: build
  script:
    - markdownlint README.md
    - markdownlint $DOCS_FOLDER/*.md
    - marp $DOCS_FOLDER/*.md --theme $MARP_CUSTOM_THEME

pages:
  stage: build
  script:
    - marp $DOCS_FOLDER/*.md --theme $MARP_CUSTOM_THEME
    - mkdir -p public/img
    - cp $DOCS_FOLDER/*.html public/
    - cp $DOCS_FOLDER/img/*.* public/img/
  artifacts:
    paths:
      - public
  only:
    - main
